version: 2.1

orbs:
  python: circleci/python@0.2.1
  docker: circleci/docker@1.0.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: python -m unittest hello.py
          name: Unit Test

  build-and-push-docker:
    docker:
      image: google/cloud-sdk:slim
    # executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: bwbeach/hello-tornado
          tag: latest
      - run:
          command: ./test-image.sh bwbeach/hello-tornado:latest
          name: Image Test
      - docker/push:
          image: bwbeach/hello-tornado
          tag: latest

workflows:
  main:
    jobs:
      - build-and-test
      - build-and-push-docker:
          filters:
            branches:
              only:
                - master
          requires:
           - build-and-test
