version: 2.1

orbs:
  python: circleci/python@0.2.1
  docker: circleci/docker@1.0.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: python -m unittest hello.py
          name: Unit Test

  build-and-push-docker:
    docker:
      - image: google/cloud-sdk:slim
    steps:
      - setup_remote_docker
      - docker/check
      # Make sure our key for google cloud is good
      - run:
          command: echo ${GOOGLE_CLOUD_KEY} | gcloud auth activate-service-account --key-file=-
      - docker/build:
          image: bwbeach/hello-tornado
          tag: latest
      - run:
          command: ./test-image.sh bwbeach/hello-tornado:latest
          name: Image Test
      - docker/push:
          image: bwbeach/hello-tornado
          tag: latest
      - run:
          command: |
            echo ${GOOGLE_CLOUD_KEY} | gcloud auth activate-service-account --key-file=-
            gcloud auth configure-docker
            gcloud config set project hello-tornado
            docker tag bwbeach/hello-tornado:latest us.gcr.io/hello-tornado/hello-tornado:latest
            docker push us.gcr.io/hello-tornado/hello-tornado:latest
            gcloud run deploy hello-tornado --image us.gcr.io/hello-tornado/hello-tornado:latest --platform managed --region us-west1

workflows:
  main:
    jobs:
      - build-and-test
      - build-and-push-docker:
          filters:
            branches:
              only:
                - master
          requires:
           - build-and-test
